ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerceapp.urls')),
    path('', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceapp/urls.py
from django.urls import path
from .views import *

app_name = "ecommerceapp"
urlpatterns = [
    path('', HomeView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('all-products/', ProductsView.as_view(), name="allproducts"),
    path('all-products/product-details', ProductDetailView.as_view(), name="productdetail"),
    path('registration/', RegistrationView.as_view(), name="registration"),
    path('logout/', LogOutView.as_view(), name="logout"),


    path('add-to-cart-<int:pro_id>/', AddToCartView.as_view(), name="addtocart"),
    path('my-cart/', MyCartView.as_view(), name="mycart"),
    path('manage-cart/<int:cp_id>/', ManageCartView.as_view(), name="managecart"),
    path('empty-cart/', EmptyCartView.as_view(), name="emptycart"),

    path('checkout/', CheckOutView.as_view(), name="checkoutcart"),
    path('profile/', CustomerProfileView.as_view(), name="customerprofile"),
    path('customerorderdetail/', CustomerOrderDetailView.as_view(), name="customerorderdetail"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name="customerorderdetail"),


]

ecommerceapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    product_title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    Category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    inventory = models.IntegerField()
    last_update = models.DateTimeField(auto_now=True)
    product_image = models.ImageField(upload_to='photos/', blank=True)

    def __str__(self):
        return self.product_title


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=255)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined = models.DateField(auto_now_add='true')

    def __str__(self):
        return self.full_name


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()


ORDER_STATUS = (
    ("Pending", "Pending"),
    ("Processing", "Processing"),
    ("Complete", "Complete"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=10)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)

    def __str__(self):
        return "Order: " + str(self.id)

ecommerceapp/forms.py
from django import forms
from .models import Order, Customer
from django.contrib.auth.models import User


class CheckOutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ("ordered_by", "shipping_address", "email", "phone_number")


class CustomerRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())

    class Meta:
        model = Customer
        fields = ("username", "full_name", "address", "password", "email")

    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError("Customer With this Username already Exists.")

        return uname


class CustomerLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

ecommerceapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from django.views.generic import TemplateView, View, CreateView, FormView, DetailView
from django.urls import reverse_lazy
from .forms import CheckOutForm, CustomerRegistrationForm, CustomerLoginForm
from django.contrib.auth import authenticate, login, logout
from django_daraja.mpesa.core import MpesaClient


# Create your views here.

class EcomMixin(object):
    def dispatch(self, request, *args, **kwargs):
        cart_id = request.session.get("cart_id")
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            if request.user.is_authenticated and request.user.customer:
                cart_obj.customer = request.user.customer
                cart_obj.save()
        return super().dispatch(request, *args, **kwargs)


class HomeView(EcomMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Product_list'] = Product.objects.all()
        return context


class ProductsView(EcomMixin, TemplateView):
    template_name = 'products.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allcategories'] = Category.objects.all()
        return context


class ProductDetailView(EcomMixin, TemplateView):
    template_name = 'productdetail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # url_slug = kwargs['slug']
        # product = Product.object.get(slug=url_slug)
        context['product'] = Product.objects.get()
        return context


class AddToCartView(EcomMixin, TemplateView):
    template_name = 'addtocart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get product id from requested url
        product_id = self.kwargs['pro_id']

        # get product
        product_obj = Product.objects.get(id=product_id)

        # check if cart exists
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            product_in_cart = cart_obj.cartproduct_set.filter(product=product_obj)
            # item already exists in cart
            if product_in_cart.exists():
                cartproduct = product_in_cart.last()
                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.price
                cartproduct.save()
                cart_obj.total += product_obj.price
                cart_obj.save()
            # new item is added in cart
            else:
                cartproduct = CartProduct.objects.create(cart=cart_obj, product=product_obj, rate=product_obj.price,
                                                         quantity=1, subtotal=product_obj.price)
                cart_obj.total += product_obj.price
                cart_obj.save()

        else:
            cart_obj = Cart.objects.create(total=0)
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(cart=cart_obj, product=product_obj, rate=product_obj.price,
                                                     quantity=1, subtotal=product_obj.price)
            cart_obj.total += product_obj.price
            cart_obj.save()

            return context


class ManageCartView(EcomMixin, View):
    def get(self, request, *args, **kwargs):
        cp_id = self.kwargs["cp_id"]
        action = request.GET.get("action")
        cp_obj = CartProduct.objects.get(id=cp_id)
        cart_obj = cp_obj.cart

        if action == "inc":
            cp_obj.quantity += 1
            cp_obj.subtotal += cp_obj.rate
            cart_obj.save()
            cart_obj.total += cp_obj.rate
            cart_obj.save()

        elif action == "dcr":
            cp_obj.quantity -= 1
            cp_obj.subtotal -= cp_obj.rate
            cp_obj.save()
            cart_obj.total -= cp_obj.rate
            cart_obj.save()
            if cp_obj.quantity == 0:
                cp_obj.delete()

        elif action == "rmv":
            cart_obj.total -= cp_obj.subtotal
            cart_obj.save()
            cp_obj.delete()

        else:
            pass
        return redirect("ecommerceapp:mycart")


class EmptyCartView(EcomMixin, View):
    def get(self, request, *args, **kwargs):
        cart_id = request.session.get("cart_id", None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
            cart.cartproduct_set.all().delete()
            cart.total = 0
            cart.save()
        return redirect("ecommerceapp:mycart")


class MyCartView(EcomMixin, TemplateView):
    template_name = 'mycart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id', None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = None
        context['cart'] = cart

        return context


class CheckOutView(EcomMixin, CreateView):
    template_name = 'checkout.html'
    form_class = CheckOutForm
    success_url = reverse_lazy("ecommerceapp:index")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.customer:
            pass
        else:
            return redirect("/login/?next=/checkout/")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
        else:
            cart_obj = None
        context['cart'] = cart_obj
        return context

    def form_valid(self, form):
        cart_id = self.request.session.get("cart_id")
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            form.instance.cart = cart_obj
            form.instance.subtotal = cart_obj.total
            form.instance.discount = 0
            form.instance.total = cart_obj.total
            form.instance.order_status = "pending"
            del self.request.session['cart_id']
        else:
            return redirect("ecommerceapp:index")
        return super().form_valid(form)


class RegistrationView(CreateView):
    template_name = 'register.html'
    form_class = CustomerRegistrationForm
    success_url = reverse_lazy("ecommerceapp:index")

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("username")
        user = User.objects.create_user(username, email, password)
        form.instance.user = user
        login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url


class LogOutView(View):
    def get(self, request):
        logout(request)
        return redirect("ecommerceapp:index")


class LoginView(FormView):
    template_name = 'login.html'
    form_class = CustomerLoginForm
    success_url = reverse_lazy("ecommerceapp:index")

    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pwd = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pwd)
        if usr is not None and Customer.objects.filter(user=usr).exists():
            login(self.request, usr)
        else:
            return render(self.request, self.template_name,
                          {"form": self.form_class, "error": "Wrong Username or Password!"})

        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url


class CustomerProfileView(FormView):
    template_name = 'profile.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.customer:
            pass
        else:
            return redirect("/login/?next=/profile/")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.request.user.customer
        context['customer'] = customer
        orders = Order.objects.filter(cart__customer=customer)
        context["orders"] = orders
        return context


class CustomerOrderDetailView(DetailView):
    template_name = "customerorderdetail.html"
    model = Order
    context_object_name = "ord_obj"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and Customer.objects.filter(user=request.user).exists():
            order_id = self.kwargs["pk"]
            order = Order.objects.get(id=order_id)
            if request.user.customer != order.cart.customer:
                return redirect("ecommerceapp:customerprofile")
        else:
            return redirect("/login/?next=/profile/")
        return super().dispatch(request, *args, **kwargs)

ecommerceapp/templates/addtocart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
     <link rel="stylesheet" href="{% static 'ecommerceapp/css/style.css' %}">
    <meta charset="UTF-8">
    <title>Add to Cart</title>
</head>
<body>
<nav>
    <ul>
    <li><a href="/all-products/">Back To Products Page</a></li>
    <li><a href="{% url 'ecommerceapp:index' %}">Back To Home page</a></li>
    <li><a href="/my-cart/">View Cart</a></li>
    <li><a href="/checkout/">CheckOut</a></li>
    </ul>
</nav>
<div>
    <h3>Product added to cart successfully</h3>
</div>
</body>
</html>

ecommerceapp/templates/checkout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'ecommerceapp/css/style.css' %}">
    <script src="https://www.paypal.com/sdk/js?client-id=AYcClgOBqEKpHNTbatdm9_qjVQKekH6tVr7U6dLcL3EuBk6d3dQ74iWPg13lcC15tIo0ta3hc7SYhCwN&currency=USD"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Checkout</title>
</head>
<body>
<nav>
    <ul>
    <li><a href="/all-products/">Back To Products Page</a></li>
    <li><a href="{% url 'ecommerceapp:index' %}">Back To Home page</a></li>
    <li><a href="/my-cart/">View Cart</a></li>
    </ul>
</nav>
<div class="container">
    <div class="row">
        <div class ="col-md-6">
            <h3>Items In the Cart</h3>
            <a href="/my-cart/">Update Cart</a>
             <table class="table">
                <thead>
                <tr>
                    <th>SN</th>
                    <th>Product</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.product_title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                 {% endfor %}
                 <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Ksh: {{cart.total}}</th>
                 </tr>
                </tbody>
             </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button>Place Order</button><br>
            </form>
            <div id="paypal-button-container"></div>
        </div>
    </div>
</div>
</body>
<script>
   paypal.Buttons({
        // Sets up the transaction when a payment button is clicked
        createOrder: (data, actions) => {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '{{cart.total}}' // Can also reference a variable or function
              }
            }]
          });
        },
        // Finalize the transaction after payer approval
        onApprove: (data, actions) => {
          return actions.order.capture().then(function(orderData) {
            // Successful capture! For dev/demo purposes:
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
            const transaction = orderData.purchase_units[0].payments.captures[0];
            alert(`Transaction ${transaction.status}: ${transaction.id}\n\nSee console for all available details`);
            // When ready to go live, remove the alert and show a success message within this page. For example:
            // const element = document.getElementById('paypal-button-container');
            // element.innerHTML = '<h3>Thank you for your payment!</h3>';
            // Or go to another URL:  actions.redirect('thank_you.html');
          });
        }
      }).render('#paypal-button-container');
</script>
</html>

ecommerceapp/templates/customerorderdetail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer Order Details</title>
</head>
<body>
<nav>
    <ul>
    <li><a href="/all-products/">Back To Products Page</a></li>
    <li><a href="{% url 'ecommerceapp:index' %}">Back To Home page</a></li>
    <li><a href="/my-cart/">View Cart</a></li>
    <li><a href="/checkout/">CheckOut</a></li>
    </ul>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3><hr>
            <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status: </span> {{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Order On: </span> {{ord_obj.created_at}}({{ord_obj.created_at|timesince}} ago)</p>
            <p><span class="font-weight-bold">Customer Information: </span> By {{ord_obj.ordered_by}}, {{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Shipping Address: </span> By {{ord_obj.shipping_address}} ({{ord_obj.email}})</p>
            <h4>Ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="_blank" href="{% url 'ecommerceapp:productdetail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a></td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total: </th>
                        <th>Rs {{ord_obj.total}}/-</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>


</body>
</html>

ecommerceapp/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login Form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'ecommerceapp/css/style2.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
   
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action="" method="POST">
        <h3>Login Here</h3>
        {% csrf_token %}
        {{form}}
       <button>Log in</button>
        <p><a href="/registration/{%if request.GET.next%}?next={{request.GET.next}}{% endif %}">Sign Up HERE</a></p>
        {% if error %}
        <li style="color:red">{{error}}</li>
        {% endif %}
    </form>

</body>
</html>

ecommerceapp/templates/mycart.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'ecommerceapp/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>My Cart</title>
</head>
<body>
<nav>
    <ul>
    <li><a href="/all-products/">Back To Products Page</a></li>
    <li><a href="{% url 'ecommerceapp:index' %}">Back To Home page</a></li>
    <li><a href="/my-cart/">View Cart</a></li>
    <li><a href="/checkout/">CheckOut</a></li>
    </ul>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items In My Cart</h4>
            <table class="table">
                <thead>
                <tr>
                    <th>SN</th>
                    <th>Product</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.product_title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href = "{% url 'ecommerceapp:managecart' cp.id%}?action=inc" class="btn btn-primary"> + </a>
                            <a href = "{% url 'ecommerceapp:managecart' cp.id%}?action=dcr" class="btn btn-warning"> - </a>
                            <a href = "{% url 'ecommerceapp:managecart' cp.id%}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>KSHS: {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="/empty-cart/" >Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a href="/checkout/">Checkout</a> </th>
                    </tr>
                    {% endif %}
                </tbody>

            </table>

        </div>

    </div>

</div>
</body>
</html>

ecommerceapp/templates/productdetail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{product.product_title}}</title>
</head>
<body>
<div class="container">
    <h3>Product: {{product.product_title}}</h3><br>
    <div class="row">
        <div class="col-md-6 margin_bottom1">
                <img src="{{p.product_image.url}}"/>
        </div>
        <div class="col-md-6">
            <h4>{{product_title}}</h4><br>
            <h5>Category: {{product.category}}</h5><br>
            <h5>Price: KSHS {{product.price}}</h5><br>
            <p>{{product.description}}</p><br>
                <a class="read_more" href="">Add to Cart</a>


    </div>


</div>

</body>
</html>

ecommerceapp/templates/products.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'ecommerceapp/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>All Products</title>
</head>
<body>
<nav>
    <ul>
    <li><a href="/all-products/">Back To Products Page</a></li>
    <li><a href="{% url 'ecommerceapp:index' %}">Back To Home page</a></li>
    <li><a href="/my-cart/">View Cart</a></li>
    <li><a href="/checkout/">CheckOut</a></li>
    </ul>
</nav>
    <div class="container">
        <h2>All Products</h2><br>
        {% for cat in allcategories %}
        <h4>{{cat.title}}</h4>
        <div class="row">
            {% for p in cat.product_set.all %}
            <div class="col-md-3">
                <div class="m-4">
                    <img src="{{p.product_image.url}}" style="height: 2500; object-fit: cover;">
                    <h4><a href="product-details">{{p.product_title}}</a></h4>
                    <h3><strong>{{p.price}}</strong></h3>
                    <a class="read_more" href="{% url 'ecommerceapp:addtocart' p.id %}">Add to Cart</a>
                </div>
            </div>
            {% endfor %}

        </div>
        {% endfor %}
    </div>



         </div>
      
    
</body>
</html>

ecommerceapp/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer Profile</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h3>Detail Information</h3><hr>
                <p><span class="font-weight-bold">Name: </span> {{customer.full_name}}</p>
                <p><span class="font-weight-bold">Username: </span> {{customer.user.username}}</p>
                <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
                <p><span class="font-weight-bold">Address: </span> {{customer.address}}</p>
                <p><span class="font-weight-bold">Joined on: </span> {{customer.joined_on}}</p>
            </div>
            <div class="col-md-8">
                <h3>Previous Orders</h3>
                <hr>
                <table class="table">
                    <thead>
                        <tr>
                            <th>SN</th>
                            <th>Order ID</th>
                            <th>Amount</th>
                            <th>Ordered on</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ord in orders %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><a href="{% url 'ecommerceapp:customerorderdetail' ord.pk %}"> #ORDER_{{ord.id}}</a></td>
                            <td>{{ord.total}}</td>
                            <td>{{ord.created_at|timesince}} ago</td>
                            <td>{{ord.order_status}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</body>
</html>

ecommerceapp/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up Form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'ecommerceapp/css/style2.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">

</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action="" method="POST">
        <h3>Sign Up Here</h3>
        {% csrf_token %}
        {{form}}
       <button>Sign Up</button>
    </form>
</body>
</html>